name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Running Java sorts tests
      working-directory: ./src/java/sorts
      run: |
        chmod +x gradlew
        ./gradlew test

    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install useful Python packages
      run: pip install pipenv

    - name: Setup Python venv and install Python dependencies
      working-directory: ./src/python/sorts
      run: |
        python -m venv venv
        source venv/bin/activate
        pipenv install

    - name: Running Python sorts tests
      working-directory: ./src/python/sorts
      run: |
        source venv/bin/activate
        pytest -v
